#!/bin/bash

echo "#SASS"
cd /var/www/.docker/server
DIR=/var/www/freeeco/landing/assets
echo "style.css"
docker-compose exec nodejs sass --scss --trace $DIR/scss/style.scss $DIR/css/style.css

echo "plugins.css"
docker-compose exec nodejs sass --scss --trace $DIR/scss/plugins.scss $DIR/css/plugins.css